module.exports = async function() {
    return [
		{ 
            "name":"Apples",
            "during":[ 
               "january",
               "february",
               "september",
               "october",
               "november",
               "december"
            ]
         },
         { 
           "name":"Bilberries",
           "during":[ 
              "june",
              "july",
              "august",
              "september",
              "october"
           ]
        },
         { 
            "name":"Blackberries",
            "during":[ 
               "july",
               "august",
               "september",
               "october"
            ]
         },
         { 
            "name":"Blackcurrants",
            "during":[ 
               "june",
               "july",
               "august"
            ]
         },
         { 
            "name":"Bramley apple",
            "during":[ 
               "january",
               "february",
               "march",
               "november",
               "december"
            ]
         },
         { 
            "name":"Cherries",
            "during":[ 
               "june",
               "july",
               "august"
            ]
         },
         { 
            "name":"Crab apple",
            "during":[ 
               "august"
            ]
         },
         { 
            "name":"Cranberries",
            "during":[ 
               "november",
               "december"
            ]
         },
         { 
            "name":"Damsons",
            "during":[ 
               "august",
               "september"
            ]
         },
         { 
            "name":"Elderberries",
            "during":[ 
               "september",
               "october"
            ]
         },
         { 
            "name":"Gooseberries",
            "during":[ 
               "june",
               "july"
            ]
         },
         { 
           "name":"Greengages",
           "during":[ 
              "july",
              "august"
           ]
        },
         { 
            "name":"Pears",
            "during":[ 
               "january",
               "february",
               "september",
               "october",
               "november",
               "december"
            ]
         },
         { 
            "name":"Plums",
            "during":[ 
               "august",
               "september"
            ]
         },
         { 
            "name":"Quince",
            "during":[ 
               "october",
               "november"
            ]
         },
         { 
            "name":"Raspberries",
            "during":[ 
               "june",
               "july",
               "august",
               "september"
            ]
         },
         { 
            "name":"Redcurrants",
            "during":[ 
               "june",
               "july",
               "august"
            ]
         },
         { 
            "name":"Rhubarb",
            "during":[ 
               "march",
               "april",
               "may",
               "june",
               "july",
               "august",
               "september"
            ]
         },
         { 
           "name":"Sloes",
           "during":[ 
              "october",
              "november",
              "december"
           ]
        },
         { 
            "name":"Strawberries",
            "during":[ 
               "may",
               "june",
               "july",
               "august"
            ]
         },
         { 
            "name":"Tomatoes",
            "during":[ 
               "june",
               "july",
               "august",
               "september",
               "october"
            ]
         }
	];
};