module.exports = async function() {
    return [
		{ 
            "name":"Basil",
            "during":[ 
               "june",
               "july",
               "august"
            ]
         },
         { 
            "name":"Chives",
            "during":[ 
               "april",
               "may",
               "june",
               "july",
               "august",
               "september",
               "october"
            ]
         },
         { 
            "name":"Chervil",
            "during":[ 
               "may",
               "june",
               "july"
            ]
         },
         { 
            "name":"Coriander",
            "during":[ 
               "may",
               "june",
               "july",
               "august",
               "september"
            ]
         },
         { 
            "name":"Dill",
            "during":[ 
               "april",
               "may",
               "june",
               "july"
            ]
         },
         { 
            "name":"Elderflowers",
            "during":[ 
               "june",
               "july"
            ]
         },
         { 
            "name":"Mint",
            "during":[ 
               "may",
               "june",
               "july",
               "august",
               "september"
            ]
         },
         { 
            "name":"Oregano",
            "during":[ 
               "may",
               "june",
               "july",
               "august",
               "september"
            ]
         },
         { 
            "name":"Parsley",
            "during":[ 
               "may",
               "june",
               "july",
               "august",
               "september",
               "october"
            ]
         },
         { 
            "name":"Rosemary",
            "during":[ 
               "may",
               "june",
               "july",
               "august",
               "september",
               "october",
               "november"
            ]
         },
         { 
            "name":"Sage",
            "during":[ 
               "may",
               "june",
               "july",
               "august",
               "september",
               "october",
               "november"
            ]
         },
         { 
            "name":"Sorrel",
            "during":[ 
               "april",
               "may",
               "june",
               "july",
               "august",
               "september",
               "october"
            ]
         },
         { 
            "name":"Tarragon",
            "during":[ 
               "may",
               "june",
               "july",
               "august"
            ]
         },
         { 
            "name":"Thyme",
            "during":[ 
               "june",
               "july",
               "august",
               "september",
               "october"
            ]
         },
         { 
            "name":"Wild nettles",
            "during":[ 
               "march",
               "april",
               "may",
               "june",
               "july"
            ]
         }
	];
};