module.exports = async function() {
    return [
		{ 
            "name":"Asparagus",
            "during":[ 
               "april",
               "may",
               "june"
            ]
         },
         { 
            "name":"Aubergine",
            "during":[ 
               "may",
               "june",
               "july",
               "august",
               "september",
               "october"
            ]
         },
         { 
            "name":"Beetroot",
            "during":[ 
               "january",
               "february",
               "march",
               "april",
               "may",
               "june",
               "july",
               "august",
               "september",
               "october",
               "november",
               "december"
            ]
         },
         { 
           "name":"Broad Beans",
           "during":[ 
              "june",
              "july",
              "august"
           ]
        },
         { 
            "name":"Broccoli",
            "during":[ 
               "march",
               "april",
               "may",
               "june",
               "july",
               "august",
               "september",
               "october"
            ]
         },
         { 
            "name":"Brussels sprouts",
            "during":[ 
               "january",
               "february",
               "march",
               "september",
               "october",
               "november",
               "december"
            ]
         },
         { 
           "name":"Butternut Squash",
           "during":[ 
              "september",
              "october",
              "november"
           ]
        },
         { 
            "name":"Cabbage",
            "during":[ 
              "january",
              "february",
              "march",
              "april",
              "may",
              "june",
              "july",
              "august",
              "september",
              "october",
              "november",
              "december"
            ]
         },
         { 
            "name":"Carrots",
            "during":[ 
               "january",
               "february",
               "march",
               "april",
               "july",
               "august",
               "september", 
               "october",
               "november",
               "december"
            ]
         },
         { 
            "name":"Cauliflower",
            "during":[ 
              "january",
              "february",
              "march",
              "april",
              "may",
              "june",
              "july",
              "august",
              "september",
              "october",
              "november",
              "december"
            ]
         },
         { 
            "name":"Cavolo nero",
            "during":[ 
               "june",
               "july",
               "august",
               "september",
               "october"
            ]
         },
         { 
            "name":"Celeriac",
            "during":[ 
               "january",
               "february",
               "march",
               "september",
               "october",
               "november",
               "december"
            ]
         },
         { 
            "name":"Celery",
            "during":[ 
               "july",
               "august",
               "september",
               "october",
               "november",
               "december"
            ]
         },
         { 
            "name":"Chicory",
            "during":[ 
              "january",
              "february",
              "march",
              "april",
              "may",
              "june",
              "july",
              "august",
              "september", 
              "october",
              "november",
              "december"
            ]
         },
         { 
           "name":"Chillies",
           "during":[ 
              "may",
              "june",
              "july",
              "august",
              "september",
              "october"
           ]
        },
         { 
            "name":"Courgette",
            "during":[ 
               "june",
               "july",
               "august",
               "september",
               "october"
            ]
         },
         { 
            "name":"Courgette flower",
            "during":[ 
               "june",
               "july",
               "august"
            ]
         },
         { 
            "name":"Fennel bulb",
            "during":[ 
               "june",
               "july"
            ]
         },
         { 
           "name":"Mushrooms",
           "during":[ 
              "january",
              "february",
              "august",
              "december"
           ]
        },
        { 
           "name":"Wild Mushrooms",
           "during":[ 
              "october",
              "november",
              "december"
           ]
        },
        { 
           "name":"French beans",
           "during":[ 
              "july",
              "august"
           ]
        },
         { 
            "name":"Garlic",
            "during":[ 
               "june",
               "july",
               "august",
               "september"
            ]
         },
         { 
            "name":"Globe artichoke",
            "during":[ 
               "june", 
               "july",
               "august",
               "september",
               "october",
               "november"
            ]
         },
         { 
            "name":"Jerusalem artichoke",
            "during":[ 
               "january",
               "february",
               "november",
               "december"
            ]
         },
         { 
            "name":"Kale",
            "during":[ 
               "january",
               "february",
               "march",
               "september",
               "october",
               "november",
               "december"
            ]
         },
         { 
            "name":"Kohlrabi",
            "during":[ 
               "july",
               "august",
               "september",
               "october",
               "november"
            ]
         },
         { 
            "name":"Lettuce",
            "during":[ 
               "may",
               "june",
               "august",
               "september",
               "october"
            ]
         },
         { 
            "name":"Leeks",
            "during":[ 
               "january",
               "february",
               "march",
               "august",
               "september",
               "october",
               "november",
               "december"
            ]
         },
         { 
           "name":"Mangetout",
           "during":[ 
              "july",
              "august",
              "september"
           ]
        },
         { 
            "name":"Marrow",
            "during":[ 
              "june",
              "july",
              "august",
              "september",
              "october"
            ]
         },
         { 
            "name":"New potatoes",
            "during":[ 
               "april",
               "may",
               "june",
               "july"
            ]
         },
         {
           "name":"Onions",
           "during":[ 
              "january",
              "february",
              "march",
              "april",
              "may",
              "june",
              "july",
              "august",
              "september",
              "october",
              "november",
              "december"
           ]
         },
         { 
            "name":"Pak choi",
            "during":[ 
               "january",
               "april",
               "may",
               "june",
               "july",
               "august",
               "september",
               "october",
               "november",
               "december"
            ]
         },
         { 
            "name":"Parsnips",
            "during":[ 
               "january",
               "february",
               "march",
               "april",
               "august",
               "september",
               "october",
               "november",
               "december"
            ]
         },
         { 
            "name":"Peas",
            "during":[ 
               "may",
               "june",
               "july",
               "august",
               "september",
               "october"
            ]
         },
         { 
            "name":"Peppers",
            "during":[ 
               "june",
               "august",
               "september"
            ]
         },
         { 
           "name":"Potatoes",
           "during":[ 
              "january",
              "february",
              "march",
              "april",
              "may",
              "june",
              "july",
              "august",
              "september",
              "october",
              "november",
              "december"
           ]
        },
         { 
            "name":"Pumpkin",
            "during":[ 
              "august",
              "september",
               "october",
               "november",
               "december"
            ]
         },
         { 
            "name":"Purple sprouting broccoli",
            "during":[ 
               "february",
               "march"
            ]
         },
         { 
            "name":"Radicchio",
            "during":[ 
               "january",
               "february",
               "march",
               "april",
               "may",
               "june",
               "july",
               "august",
               "september",
               "october",
               "november",
               "december"
            ]
         },
         { 
            "name":"Radishes",
            "during":[ 
               "april",
               "may",
               "june",
               "july",
               "august",
               "september",
               "october"
            ]
         },
         { 
           "name":"Rocket",
           "during":[ 
              "april",
              "may",
              "june",
              "july",
              "august",
              "september",
              "october"
           ]
        },
         { 
            "name":"Runner beans",
            "during":[ 
               "july",
               "august",
               "september",
               "october"
            ]
         },
         { 
            "name":"Salsify",
            "during":[ 
               "january",
               "october",
               "november",
               "december"
            ]
         },
         { 
            "name":"Samphire",
            "during":[ 
               "may",
               "june",
               "july",
               "august",
               "september"
            ]
         },
         { 
           "name":"Shallots",
           "during":[ 
              "january",
              "february",
              "september",
              "october",
              "november",
              "december"
           ]
        },
         { 
            "name":"Spinach",
            "during":[ 
               "april",
               "may",
               "september",
               "october"
            ]
         },
         { 
           "name":"Spring Onions",
           "during":[ 
              "january",
              "february",
              "march",
              "april",
              "may",
              "june",
              "july",
              "august",
              "september",
              "october"
           ]
        },
         { 
            "name":"Spring Greens",
            "during":[ 
               "january",
               "february",
               "march",
               "april",
               "may",
               "june",
               "july",
               "august",
               "september",
               "october"
            ]
         },
         { 
            "name":"Swede",
            "during":[ 
               "january",
               "february",
               "march",
               "july",
               "august",
               "september",
               "october",
               "november",
               "december"
            ]
         },
         { 
            "name":"Sweetcorn",
            "during":[ 
               "august",
               "september", 
               "october"
            ]
         },
         { 
            "name":"Swiss chard",
            "during":[ 
               "july",
               "august",
               "september",
               "october",
               "november",
               "december"
            ]
         },
         { 
            "name":"Turnips",
            "during":[ 
               "january",
               "february",
               "september",
               "october",
               "november",
               "december"
            ]
         },
         { 
            "name":"Watercress",
            "during":[ 
               "march",
               "april",
               "may",
               "june",
               "july",
               "august",
               "september",
               "october",
               "november"
            ]
         }
	];
};